# endpoints will default to polkachu if unset
#rpc_endpoint = "https://localhost:26657"
#grpc_endpoint = "https://localhost:9090"

[[orders]]
fee_token = "gravity0xd35CCeEAD182dcee0F148EbaC9447DA2c4D449c4"
maximum_usomm_in = 25000000
minimum_usd_value_out = 100.00

[[orders]]
fee_token = "gravity0xd35CCeEAD182dcee0F148EbaC9447DA2c4D449c4"
maximum_usomm_in = 26000000
minimum_usd_value_out = 100.00

