[package]
name = "auction-bot"
version = "0.1.0"
verson.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sommelier-auction.workspace = true
price_feed.workspace = true
sommelier-auction-order-engine.workspace = true
sommelier-auction-proto.workspace = true
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros"] }
clap = { version = "4.4.6", features = ["derive"] }
tracing.workspace = true
tracing-subscriber.workspace = true
